/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormularioJogo.java
 *
 * Created on 20/06/2010, 01:24:02
 */

/**
 *
 * @author gustavo
 */
public class FormularioJogo extends javax.swing.JFrame {
    JogoDaVelha jogo;
    Jogador jogador1, jogador2, velha;

    /** Creates new form FormularioJogo */
    public FormularioJogo(JogoDaVelha j, Jogador j1, Jogador j2, Jogador v) {
        initComponents();
        jogo = j;
        jogador1 = j1;
        jogador2 = j2;
        velha = v;
        Jogador1.setText("" + j1.letra + ": ");
        Jogador2.setText("" + j2.letra + ": ");
        Velha.setText("Velha: ");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Vencedor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Mesa = new javax.swing.JTextPane();
        Jogador2 = new javax.swing.JLabel();
        Jogador1 = new javax.swing.JLabel();
        Jogador1Vitorias = new javax.swing.JLabel();
        Jogador2Vitorias = new javax.swing.JLabel();
        Velha = new javax.swing.JLabel();
        VelhaVitorias = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mesa");

        jButton1.setText("Gerar Jogadas Aleatórias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Vencedor:");

        jScrollPane1.setViewportView(Mesa);

        Jogador2.setText("Jogador 2:");

        Jogador1.setText("Jogador 1:");

        Jogador1Vitorias.setText("0");

        Jogador2Vitorias.setText("0");

        Velha.setText("Velha:");

        VelhaVitorias.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Vencedor))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jogador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jogador2Vitorias))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Jogador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jogador1Vitorias))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Velha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VelhaVitorias)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Velha)
                    .addComponent(VelhaVitorias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Jogador1Vitorias)
                    .addComponent(Jogador1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jogador2Vitorias)
                    .addComponent(Jogador2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Vencedor))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jogo.GeraJogadasAleatorias(jogador1, jogador2);
        atualiza();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void atualiza() {
        char vencedor = jogo.verificaJogo();
        Mesa.setText(jogo.mesa.toString());
        if(vencedor != jogador1.letra && vencedor != jogador2.letra)
            Vencedor.setText("Velha");
        else
            Vencedor.setText("" + vencedor);
        Jogador1Vitorias.setText("" + jogador1.vitorias);
        Jogador2Vitorias.setText("" + jogador2.vitorias);
        VelhaVitorias.setText("" + velha.vitorias);
    }
    /**
    * @param args the command line arguments
    */    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jogador1;
    private javax.swing.JLabel Jogador1Vitorias;
    private javax.swing.JLabel Jogador2;
    private javax.swing.JLabel Jogador2Vitorias;
    private javax.swing.JTextPane Mesa;
    private javax.swing.JLabel Velha;
    private javax.swing.JLabel VelhaVitorias;
    private javax.swing.JLabel Vencedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
